/**
 * Known-diplotype fixtures.
 *
 * The demo runs on these so it cannot fail on live variant calling. They are not shortcuts
 * around the pipeline: each fixture is a set of genotype calls that flows through exactly
 * the same star-allele caller, confidence scorer and ranking engine as an uploaded file.
 * The only thing fixed is the input.
 *
 * Each fixture also renders to a downloadable 23andMe-format export, so the upload path can
 * be exercised for real rather than described.
 */

import { excludedGeneCalls } from '../../data/excluded-genes'
import type { AssayType, PharmCATReport } from '../types'
import {
  buildGeneCalls,
  genotypeOnlyRecommendations,
  VARIANTS,
  type GenomeInput,
  type PharmCATAdapter,
} from './adapter'

export interface Fixture {
  id: string
  title: string
  /** What this fixture is for, shown in the demo picker. */
  story: string
  assayType: AssayType
  fileName: string
  /** rsid -> genotype, plus-strand as a consumer export reports it. */
  calls: Record<string, string>
  /** Suggested current medications and past trials for this fixture. */
  suggestedMedications: string[]
  suggestedTrials: Array<{ drug: string; outcome: 'no_effect' | 'side_effects' | 'helped' }>
}

export const FIXTURES: Fixture[] = [
  {
    id: 'demo-phenoconversion',
    title: 'The phenoconversion case',
    story:
      'Genetically an ordinary CYP2D6 metaboliser, but currently taking fluoxetine — which is a strong ' +
      'inhibitor of both CYP2D6 and CYP2C19. Two antidepressants have already been tried without success.',
    assayType: 'consumer-array',
    fileName: 'genome_demo_phenoconversion.txt',
    calls: {
      rs4244285: 'AG', // CYP2C19*2 heterozygous -> *1/*2 intermediate
      rs4986893: 'GG', // no *3
      rs12248560: 'CC', // no *17
      rs3892097: 'GG', // no CYP2D6*4
      rs1065852: 'GG', // no CYP2D6*10 -> *1/*1, activity score 2.0
      rs3745274: 'GG', // no CYP2B6*6
    },
    suggestedMedications: ['fluoxetine'],
    suggestedTrials: [
      { drug: 'paroxetine', outcome: 'side_effects' },
      { drug: 'escitalopram', outcome: 'no_effect' },
    ],
  },
  {
    id: 'demo-ultrarapid',
    title: 'The ultrarapid metaboliser',
    story:
      'Carries two copies of CYP2C19*17 and clears the CYP2C19 antidepressants unusually fast. Three drugs ' +
      'have been recorded as "no effect", which is exactly what underexposure looks like from the outside.',
    assayType: 'consumer-array',
    fileName: 'genome_demo_ultrarapid.txt',
    calls: {
      rs4244285: 'GG',
      rs4986893: 'GG',
      rs12248560: 'TT', // *17/*17 -> ultrarapid
      rs3892097: 'GG',
      rs1065852: 'GG',
      rs3745274: 'GG',
    },
    suggestedMedications: [],
    suggestedTrials: [
      { drug: 'escitalopram', outcome: 'no_effect' },
      { drug: 'citalopram', outcome: 'no_effect' },
    ],
  },
  {
    id: 'demo-poor-metaboliser',
    title: 'The genuine poor metaboliser',
    story:
      'Two non-functional CYP2D6 alleles, so this is a poor metaboliser on genotype alone with no interacting ' +
      'medication involved. Side effects arrived within days on the last two attempts.',
    assayType: 'targeted-pgx',
    fileName: 'genome_demo_poor_metaboliser.txt',
    calls: {
      rs4244285: 'GG',
      rs4986893: 'GG',
      rs12248560: 'CC',
      rs3892097: 'AA', // *4/*4 -> activity score 0, poor metaboliser
      rs1065852: 'AA',
      rs3745274: 'GG',
    },
    suggestedMedications: [],
    suggestedTrials: [
      { drug: 'paroxetine', outcome: 'side_effects' },
      { drug: 'venlafaxine', outcome: 'side_effects' },
    ],
  },
]

export function fixtureById(id: string): Fixture | undefined {
  return FIXTURES.find((f) => f.id === id)
}

/** Renders a fixture as a 23andMe-format raw export, so the upload path can be tested. */
export function fixtureToFileText(fixture: Fixture): string {
  const header = [
    '# This data file generated by the antidepressant PGx prototype as a test fixture.',
    '# Format matches a 23andMe raw export: rsid, chromosome, position, genotype.',
    '# Positions are GRCh38, read from PharmCAT\'s shipped pharmcat_positions.vcf.',
    `# Fixture: ${fixture.id} — ${fixture.title}`,
    '#',
    '# rsid\tchromosome\tposition\tgenotype',
  ].join('\n')

  const rows = VARIANTS.filter((v) => fixture.calls[v.rsid]).map((v) =>
    [v.rsid, v.chrom.replace('chr', ''), String(v.position), fixture.calls[v.rsid]].join('\t'),
  )

  return `${header}\n${rows.join('\n')}\n`
}

export class FixturePharmCATAdapter implements PharmCATAdapter {
  readonly name = 'Known-diplotype fixture'
  readonly provenance = 'fixture' as const

  constructor(private readonly fixture: Fixture) {}

  async analyze(_input: GenomeInput): Promise<PharmCATReport> {
    const genes = buildGeneCalls(this.fixture.calls, this.fixture.assayType)
    return {
      reportId: this.fixture.id,
      provenance: 'fixture',
      pharmcatVersion: 'fixture diplotypes; guideline data from CPIC as bundled by PharmCAT',
      assayType: this.fixture.assayType,
      genes,
      excludedGenes: excludedGeneCalls({}),
      recommendations: genotypeOnlyRecommendations(genes),
    }
  }
}
